FROM node:16-bullseye

RUN apt update
RUN apt -y install build-essential python3 python3-pip python3-dev python3-numpy python3-pandas python3-nltk g++

RUN pip3 install --upgrade gensim
RUN pip3 install --upgrade spacy
RUN pip3 install --upgrade sentence_transformers
RUN pip3 install --upgrade google-cloud-language

ENV NODE_ENV=development
ENV NPM_CONFIG_PREFIX=/home/node/.npm-global
ENV PATH=$PATH:/home/node/.npm-global/bin

WORKDIR /home/node

COPY app/package.json .
COPY app/package-lock.json .
RUN npm install

COPY app .
RUN python3 -m spacy download en_core_web_lg
RUN python3 -c "import nltk;nltk.download('punkt')"
RUN python3 -c "import nltk;nltk.download('stopwords')"

USER node
RUN python3 -c "from sentence_transformers import SentenceTransformer; SentenceTransformer('all-mpnet-base-v2', cache_folder='/tmp/.cache')"

ENV NODE_ENV=development
EXPOSE 8000
CMD ["npm", "run", "dev:services"]
